server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /
    
spring: 
    application:
      name: spring_cloud
   
org: 
  zoo:
    swan: 
      started: true
      mode-type: header
      application-name: yst-tms-admin
      token-support: uuid
      token-key: YST_ADMIN_KEY
      swan-redis-config:
#       #cluster集群
        cluster: true
        cluster-servers-config:
          node-addresses:
          - redis://10.213.3.107:6379
          - redis://10.213.6.159:6379
          - redis://10.213.3.105:6379
          - redis://10.213.3.17:6379
          - redis://10.213.3.18:6379
          - redis://10.213.3.19:6379
          
          
#        #redis单点配置      
#         single: true
#         single-server-config: 
#           address: redis://127.0.0.1:6379
          


logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.zoo.cat.bonuspoint: debug
        org.zoo.cat.lottery: debug
        org.zoo.cat: debug
        io.netty: info
    path: "./logs"

